import { ensureOpenClawPackageResolution } from './src/bootstrap/openclaw-host-link';

await ensureOpenClawPackageResolution(import.meta.url);

const entry = await import('./src/plugin-entry');

const plugin = entry.default;
const {
  monitorFeishuProvider,
  sendMessageFeishu,
  sendCardFeishu,
  updateCardFeishu,
  editMessageFeishu,
  getMessageFeishu,
  uploadImageLark,
  uploadFileLark,
  sendImageLark,
  sendFileLark,
  sendAudioLark,
  uploadAndSendMediaLark,
  sendTextLark,
  sendCardLark,
  sendMediaLark,
  probeFeishu,
  addReactionFeishu,
  removeReactionFeishu,
  listReactionsFeishu,
  FeishuEmoji,
  VALID_FEISHU_EMOJI_TYPES,
  forwardMessageFeishu,
  updateChatFeishu,
  addChatMembersFeishu,
  removeChatMembersFeishu,
  listChatMembersFeishu,
  feishuMessageActions,
  mentionedBot,
  nonBotMentions,
  extractMessageBody,
  formatMentionForText,
  formatMentionForCard,
  formatMentionAllForText,
  formatMentionAllForCard,
  buildMentionedMessage,
  buildMentionedCardContent,
  feishuPlugin,
  handleFeishuReaction,
  parseMessageEvent,
  checkMessageGate,
  isMessageExpired,
} = entry;

export default plugin;
export {
  FeishuEmoji,
  VALID_FEISHU_EMOJI_TYPES,
  addChatMembersFeishu,
  addReactionFeishu,
  buildMentionedCardContent,
  buildMentionedMessage,
  checkMessageGate,
  editMessageFeishu,
  extractMessageBody,
  feishuMessageActions,
  feishuPlugin,
  formatMentionAllForCard,
  formatMentionAllForText,
  formatMentionForCard,
  formatMentionForText,
  forwardMessageFeishu,
  getMessageFeishu,
  handleFeishuReaction,
  isMessageExpired,
  listChatMembersFeishu,
  listReactionsFeishu,
  mentionedBot,
  monitorFeishuProvider,
  nonBotMentions,
  parseMessageEvent,
  probeFeishu,
  removeChatMembersFeishu,
  removeReactionFeishu,
  sendAudioLark,
  sendCardFeishu,
  sendCardLark,
  sendFileLark,
  sendImageLark,
  sendMediaLark,
  sendMessageFeishu,
  sendTextLark,
  updateCardFeishu,
  updateChatFeishu,
  uploadAndSendMediaLark,
  uploadFileLark,
  uploadImageLark,
};

export type {
  FeishuChannelData,
  FeishuMessageContext,
  FeishuReactionCreatedEvent,
  MentionInfo,
  MessageContext,
  RawMessage,
  RawSender,
  SendCardLarkParams,
  SendMediaLarkParams,
  SendTextLarkParams,
} from './src/plugin-entry';
