import { ensureOpenClawPackageResolutionSync } from './src/bootstrap/openclaw-host-link';

ensureOpenClawPackageResolutionSync(import.meta.url);

export { default } from './src/plugin-entry';
export {
  monitorFeishuProvider,
  sendMessageFeishu,
  sendCardFeishu,
  updateCardFeishu,
  editMessageFeishu,
  getMessageFeishu,
  uploadImageLark,
  uploadFileLark,
  sendImageLark,
  sendFileLark,
  sendAudioLark,
  uploadAndSendMediaLark,
  sendTextLark,
  sendCardLark,
  sendMediaLark,
  probeFeishu,
  addReactionFeishu,
  removeReactionFeishu,
  listReactionsFeishu,
  FeishuEmoji,
  VALID_FEISHU_EMOJI_TYPES,
  forwardMessageFeishu,
  updateChatFeishu,
  addChatMembersFeishu,
  removeChatMembersFeishu,
  listChatMembersFeishu,
  feishuMessageActions,
  mentionedBot,
  nonBotMentions,
  extractMessageBody,
  formatMentionForText,
  formatMentionForCard,
  formatMentionAllForText,
  formatMentionAllForCard,
  buildMentionedMessage,
  buildMentionedCardContent,
  feishuPlugin,
  handleFeishuReaction,
  parseMessageEvent,
  checkMessageGate,
  isMessageExpired,
} from './src/plugin-entry';
export type {
  FeishuChannelData,
  FeishuMessageContext,
  FeishuReactionCreatedEvent,
  MentionInfo,
  MessageContext,
  RawMessage,
  RawSender,
  SendCardLarkParams,
  SendMediaLarkParams,
  SendTextLarkParams,
} from './src/plugin-entry';
